apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.productpage.namespace }}
spec:
  type: {{ .Values.ingress.serviceType | default "ClusterIP" }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.productpage.port }}
      targetPort: {{ .Values.productpage.port }}
      protocol: TCP
      name: http