apiVersion: v1
kind: Service
metadata:
  name: bookinfo-dev-ratings
  namespace: bookinfo-dev
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: bookinfo-dev-ratings
  ports:
    - port: 8080
      targetPort: 8080
