apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-dev-ratings
  namespace: bookinfo-dev
  labels:
    app: bookinfo-dev-ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookinfo-dev-ratings
  template:
    metadata:
      labels:
        app: bookinfo-dev-ratings
    spec:
      containers:
        - name: bookinfo-dev-ratings
          image: registry-gital.opsta.in.th/bookinfo/ratings:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web-port
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
          env:
            - name: SERVICE_VERSION
              value: v2
            - name: MONGO_DB_URL
              value: mongodb://bookinfo-dev-ratings-mongodb:27017
            - name: MONGO_DB_NAME
              value: bookinfo-dev-ratings
            - name: MONGO_DB_USERNAME
              value: root
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookinfo-dev-ratings-mongo-secret
                  key: mongodb-passwords
      imagePullSecrets:
        - name: registry-bookinfo
