apiVersion: v1
description: Bookinfo Reviews Service Helm Chart
name: bookinfo-reviews
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo-gital-dev.opsta.in.th/reviews
maintainers:
  - name: Phattaratorn Mahatkeerati
