externalURL: https://registry-gital.opsta.in.th

expose:
  type: ingress
  ingress:
    controller: default
    className: nginx
    hosts:
      core: registry-gital.opsta.in.th
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "900"
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"

persistence:
  enabled: true

tls:
  enabled: true
  secretName: harbor-origin-cert