apiVersion: v1
description: Bookinfo Details Service Helm Chart
name: bookinfo-details
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo-gital-dev.opsta.in.th/details
maintainers:
  - name: Phattaratorn Mahatkeerati
