apiVersion: v1
description: Bookinfo Productpage Service Helm Chart
name: bookinfo-productpage
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo-gital-dev.opsta.in.th/productpage
maintainers:
  - name: Phattaratorn Mahatkeerati
