productpage:
  namespace: bookinfo-uat
  image: registry-gital.opsta.in.th/bookinfo/productpage
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9000
  healthCheckPath: "/health"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  host: bookinfo-gital-uat.opsta.in.th
  path: /
  pathType: Prefix
  serviceType: ClusterIP
extraEnv:
  DETAILS_HOSTNAME: http://bookinfo-details-uat:9080
  RATINGS_HOSTNAME: http://bookinfo-ratings-uat:8080
  REVIEWS_HOSTNAME: http://bookinfo-reviews-uat:9080
  FLOOD_FACTOR: 0
  COMMIT_ID: CHANGEME
