productpage:
  namespace: bookinfo-uat
  image: registry-gital.opsta.in.th/bookinfo/productpage
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9000
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "bookinfo-ip"
    ingress.gcp.kubernetes.io/pre-shared-cert: "bookinfo-gital-uat-cert"
    kubernetes.io/ingress.allow-http: false
  host: bookinfo-gital-uat.opsta.in.th
  path: /*
  serviceType: NodePort
extraEnv:
  DETAILS_HOSTNAME: http://bookinfo-details-uat:9080
  RATINGS_HOSTNAME: http://bookinfo-ratings-uat:8080
  REVIEWS_HOSTNAME: http://bookinfo-reviews-uat:9080
  FLOOD_FACTOR: 0
