productpage:
  namespace: bookinfo-dev
  image: registry-gital.opsta.in.th/bookinfo/productpage
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9000
  healthCheckPath: "/health"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
  host: bookinfo-gital-dev.opsta.in.th
  path: /
  pathType: Prefix
  serviceType: ClusterIP
extraEnv:
  DETAILS_HOSTNAME: http://bookinfo-details-dev:9080
  RATINGS_HOSTNAME: http://bookinfo-ratings-dev:8080
  REVIEWS_HOSTNAME: http://bookinfo-reviews-dev:9080
  FLOOD_FACTOR: 0
