productpage:
  namespace: bookinfo-dev
  image: registry-gital.opsta.in.th/bookinfo/productpage
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9000
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.global-static-ip-name: "bookinfo-ip"
    ingress.gcp.kubernetes.io/pre-shared-cert: "bookinfo-gital-dev-cert"
    kubernetes.io/ingress.allow-http: false
  host: bookinfo-gital-dev.opsta.in.th
  path: /*
  serviceType: NodePort
extraEnv:
  DETAILS_HOSTNAME: http://bookinfo-details-dev:9080
  RATINGS_HOSTNAME: http://bookinfo-ratings-dev:8080
  REVIEWS_HOSTNAME: http://bookinfo-reviews-dev:9080
  FLOOD_FACTOR: 0
