details:
  namespace: bookinfo-prd
  image: registry-gital.opsta.in.th/bookinfo/details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
extraEnv: {
  COMMIT_ID: CHANGEME
}
