details:
  namespace: bookinfo-prd
  image: registry-gital.opsta.in.th/bookinfo/details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "bookinfo-ip"
    ingress.gcp.kubernetes.io/pre-shared-cert: "bookinfo-gital-prd-cert"
    kubernetes.io/ingress.allow-http: false
  host: bookinfo-gital-prd.opsta.in.th
  path: /details/*
  serviceType: NodePort
extraEnv: {}
