ratings:
  namespace: bookinfo-prd
  image: registry-gital.opsta.in.th/bookinfo/ratings
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-prd-ratings-mongo-secret
ingress:
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "bookinfo-ip"
    ingress.gcp.kubernetes.io/pre-shared-cert: "bookinfo-gital-dev-cert"
    kubernetes.io/ingress.allow-http: false
  host: bookinfo-gital-prd.opsta.in.th
  path: /ratings/*
  serviceType: NodePort
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-prd-ratings-mongodb:27017
  MONGO_DB_USERNAME: root
  MONGO_DB_NAME: bookinfo-prd-ratings
