image:
  tag: latest
auth:
  existingSecret: bookinfo-prod-ratings-mongo-secret
  username: ratings-prod
  database: ratings-prod
persistence:
  enabled: false
initdbScriptsConfigMap: bookinfo-prod-ratings-mongodb-initdb
extraEnvVars: # For declaring additional environment variable in pods
  - name: MONGODB_USERNAME
    value: "root"
  - name: MONGODB_DATABASE
    value: "bookinfo-prod-ratings"
  - name: MONGODB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: bookinfo-prod-ratings-mongo-secret
        key: mongodb-passwords
