ratings:
  namespace: bookinfo-uat
  image: registry-gital.opsta.in.th/bookinfo/ratings
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
  mongodbPasswordExistingSecret: bookinfo-uat-ratings-mongo-secret
extraEnv:
  SERVICE_VERSION: v2
  MONGO_DB_URL: mongodb://bookinfo-uat-ratings-mongodb:27017
  MONGO_DB_USERNAME: root
  MONGO_DB_NAME: bookinfo-uat-ratings
